// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NotifierServiceClient is the client API for NotifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierServiceClient interface {
	Subscribe(ctx context.Context, in *NotificationSubscriber, opts ...grpc.CallOption) (NotifierService_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *NotificationSubscriber, opts ...grpc.CallOption) (*NotificationDone, error)
	Broadcast(ctx context.Context, in *NotificationData, opts ...grpc.CallOption) (*NotificationDone, error)
}

type notifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierServiceClient(cc grpc.ClientConnInterface) NotifierServiceClient {
	return &notifierServiceClient{cc}
}

func (c *notifierServiceClient) Subscribe(ctx context.Context, in *NotificationSubscriber, opts ...grpc.CallOption) (NotifierService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NotifierService_serviceDesc.Streams[0], "/notifierserver.NotifierService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &notifierServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NotifierService_SubscribeClient interface {
	Recv() (*NotificationData, error)
	grpc.ClientStream
}

type notifierServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *notifierServiceSubscribeClient) Recv() (*NotificationData, error) {
	m := new(NotificationData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *notifierServiceClient) Unsubscribe(ctx context.Context, in *NotificationSubscriber, opts ...grpc.CallOption) (*NotificationDone, error) {
	out := new(NotificationDone)
	err := c.cc.Invoke(ctx, "/notifierserver.NotifierService/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierServiceClient) Broadcast(ctx context.Context, in *NotificationData, opts ...grpc.CallOption) (*NotificationDone, error) {
	out := new(NotificationDone)
	err := c.cc.Invoke(ctx, "/notifierserver.NotifierService/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifierServiceServer is the server API for NotifierService service.
// All implementations must embed UnimplementedNotifierServiceServer
// for forward compatibility
type NotifierServiceServer interface {
	Subscribe(*NotificationSubscriber, NotifierService_SubscribeServer) error
	Unsubscribe(context.Context, *NotificationSubscriber) (*NotificationDone, error)
	Broadcast(context.Context, *NotificationData) (*NotificationDone, error)
	mustEmbedUnimplementedNotifierServiceServer()
}

// UnimplementedNotifierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServiceServer struct {
}

func (UnimplementedNotifierServiceServer) Subscribe(*NotificationSubscriber, NotifierService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNotifierServiceServer) Unsubscribe(context.Context, *NotificationSubscriber) (*NotificationDone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedNotifierServiceServer) Broadcast(context.Context, *NotificationData) (*NotificationDone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedNotifierServiceServer) mustEmbedUnimplementedNotifierServiceServer() {}

// UnsafeNotifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServiceServer will
// result in compilation errors.
type UnsafeNotifierServiceServer interface {
	mustEmbedUnimplementedNotifierServiceServer()
}

func RegisterNotifierServiceServer(s grpc.ServiceRegistrar, srv NotifierServiceServer) {
	s.RegisterService(&_NotifierService_serviceDesc, srv)
}

func _NotifierService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotificationSubscriber)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotifierServiceServer).Subscribe(m, &notifierServiceSubscribeServer{stream})
}

type NotifierService_SubscribeServer interface {
	Send(*NotificationData) error
	grpc.ServerStream
}

type notifierServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *notifierServiceSubscribeServer) Send(m *NotificationData) error {
	return x.ServerStream.SendMsg(m)
}

func _NotifierService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationSubscriber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifierserver.NotifierService/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServiceServer).Unsubscribe(ctx, req.(*NotificationSubscriber))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifierService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifierserver.NotifierService/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServiceServer).Broadcast(ctx, req.(*NotificationData))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotifierService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notifierserver.NotifierService",
	HandlerType: (*NotifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unsubscribe",
			Handler:    _NotifierService_Unsubscribe_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _NotifierService_Broadcast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _NotifierService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notification.proto",
}
